version: '3'

services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    command: npm run start
    restart: unless-stopped
    volumes:
      - ./protobufs:/usr/src/protobufs
    ports:
      - "3001:3001"
    networks:
      - habranews

  user-service:
    build: ./user-service
    container_name: user-service
    command: npm run start
    restart: unless-stopped
    volumes:
      - ./protobufs:/usr/src/protobufs
    networks:
      - habranews

networks:
  habranews:
    driver: bridge
