version: '3.3'

services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    command: npm run start
    restart: unless-stopped
    volumes:
      - ./protobufs:/usr/src/protobufs
    ports:
      - "3001:3001"
    networks:
      - habranews
    depends_on: 
      - user-service

  user-service:
    build: ./user-service
    container_name: user-service
    command: npm run start
    restart: unless-stopped
    volumes:
      - ./protobufs:/usr/src/protobufs
    networks:
      - habranews

  user-service-db:
    container_name: user-service-db
    image: postgres
    ports: 
      - "5433:5433"
    env_file: 
      - ./user-service-db/postgresql.env
    volumes: 
      - user-service-db-volume:/var/lib/postgresql/data
    networks: 
      - habranews

volumes:
  user-service-db-volume:

networks:
  habranews:
    driver: bridge

# psql --username=ythosa --port=5433 --dbname=userservice
